arch: require arch-syscall-dump from arch-syscall-validate
The arch-syscall-dump is almost always used from arch-syscall-validate
(the only exception I found is when -c and -l are given), so it makes
sense to check that it's available beforehand.

Without this patch, when arch-syscall-dump is not present, the script
produces lots of output with a few errors about the missing
./arch-syscall-dump hidden in the middle of it.

To keep things simple, we require arch-syscall-dump even when it is not
going to be used.

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
Acked-by: Paul Moore <paul@paul-moore.com>
Signed-off-by: Tom Hromatka <tom.hromatka@oracle.com>

diff --git a/src/arch-syscall-validate b/src/arch-syscall-validate
--- a/src/arch-syscall-validate
+++ b/src/arch-syscall-validate
@@ -845,10 +845,6 @@ while getopts "a:c:slh" opt; do
 		opt_lib=0
 		;;
 	l)
-		if [[ ! -x $LIB_SYS_DUMP ]]; then
-			echo "error: \"$LIB_SYS_DUMP\" is not present"
-			exit 1
-		fi
 		opt_sys=0
 		opt_lib=1
 		;;
@@ -880,6 +876,11 @@ if [[ -z $kernel_dir ]]; then
 fi
 if [[ ! -d $kernel_dir ]]; then
 	echo "error: \"$1\" is not a valid directory"
+	exit 1
+fi
+
+if [[ ! -x "$LIB_SYS_DUMP" ]]; then
+	echo "error: \"$LIB_SYS_DUMP\" is not present"
 	exit 1
 fi
 
